# Generated by Django 3.2.7 on 2021-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0002_plantdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(default=None)),
                ('ProductID', models.IntegerField(default=None)),
                ('ProdName', models.CharField(default=None, max_length=100)),
                ('Prod_qty', models.IntegerField(default=None)),
                ('Prod_Price', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'CartItems',
            },
        ),
        migrations.CreateModel(
            name='cartproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(default=None, max_length=100)),
                ('ProdId', models.CharField(default=None, max_length=100)),
                ('ProdName', models.CharField(default=None, max_length=100)),
                ('UserID', models.IntegerField(default=None)),
                ('Prodqty', models.IntegerField(default=None)),
                ('ProdPrice', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'cartproducts',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.CharField(default=None, max_length=200)),
                ('TotalPrice', models.CharField(default=None, max_length=200)),
                ('OrderDate', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'OrderDetail',
            },
        ),
        migrations.AlterModelTable(
            name='plantdetails',
            table='PlantDetails',
        ),
    ]
