# Generated by Django 3.2.7 on 2021-09-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0003_auto_20210917_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(default=None)),
                ('FlowerID', models.IntegerField(default=None)),
                ('Fname', models.CharField(default=None, max_length=100)),
                ('Type', models.CharField(default=None, max_length=100)),
                ('Price', models.BigIntegerField(default=None)),
            ],
            options={
                'db_table': 'Favourite',
            },
        ),
    ]
