# Generated by Django 3.2.7 on 2021-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0004_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustID', models.IntegerField(default=None)),
                ('Name', models.CharField(default=None, max_length=200)),
                ('Email', models.EmailField(default=None, max_length=200)),
                ('Phone', models.IntegerField(default=None)),
                ('messages', models.CharField(default=None, max_length=200)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
