# Generated by Django 3.2.9 on 2021-12-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdetails',
            name='Pictures',
            field=models.ImageField(default=None, upload_to='Images'),
        ),
    ]
