# Generated by Django 3.2.12 on 2022-03-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0007_auto_20220301_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellLogin',
        ),
    ]
