# Generated by Django 3.2.12 on 2022-03-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppGoGreen', '0008_delete_selllogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerRegisteration',
            new_name='SellerRegisterations',
        ),
        migrations.AlterModelTable(
            name='sellerregisterations',
            table='SellerRegisterations',
        ),
    ]
